### ISSUE TITLE
Generate more compact datasets

### ISSUE THREAD

**Issue by moreymat** [kowey/educe#25]
The tab formatted output by educe is currently a dense table whose values are mostly strings.
While these strings make the format reasonably readable for humans, they are quite memory intensive when loaded by a machine.

Downstream components pay this price as well, e.g. loading two 150MB files (300MB total) in `attelo` results in 620 and 560 MB used in RAM:

```
(irit-rst-dt)➜  irit-rst-dt git:(master) ✗ ls -l TMP/latest/
-rw-r--r-- 6 mathieu mathieu 150263912 déc.  12 15:55 RSTtrees-WSJ-double-1.0.edu-pairs.tab
-rw-r--r-- 6 mathieu mathieu 151560005 déc.  12 15:55 RSTtrees-WSJ-double-1.0.relations.tab
```

```
Filename: /home/mathieu/travail/recherche/melodi/attelo/attelo/io.py

Line #    Mem usage    Increment   Line Contents
================================================
    88   38.473 MiB    0.000 MiB   @profile
    89                             def read_data(attachments, relations, verbose=False):
    90                                 """
    91                                 Given an attachment file and a relations file (latter can
    92                                 be None, return their contents in table form)
    93                                 """
    94   38.473 MiB    0.000 MiB       with Torpor("Reading attachments", quiet=not verbose):
    95  657.809 MiB  619.336 MiB           data_attach = Orange.data.Table(attachments)
    96                             
    97  657.809 MiB    0.000 MiB       if relations is None:
    98                                     data_relations = None
    99                                 else:
   100  657.809 MiB    0.000 MiB           with Torpor("Reading relations", quiet=not verbose):
   101 1220.148 MiB  562.340 MiB               data_relations = Orange.data.Table(relations)
   102 1220.148 MiB    0.000 MiB       return data_attach, data_relations
```

We can avoid this by building a mapping between (feature name, feature value) and integer identifiers, saving this mapping in a file and outputting integers in the sample files.

**Comment by moreymat** [comment]
On the full TRAINING set of the RST-DT treebank, the sparse file (svmlight/libsvm format):
* weighs 860MB (vs 960MB for Orange tab),
* takes 1460MB of RAM when loaded with scikit-learn (which I simply could not do with Orange).

This overhead (again, just to load the dataset) seems way more reasonable and confirms scikit-learn is the way to go.

**Comment by kowey** [comment]
I think this is resolved by all the scikit work.  Thanks for pushing this all forward!
